// src/harness/vue/DefaultHarness.vue
<script setup lang="ts">
import ComponentHarness from './ComponentHarness.vue'
import ComponentHarnessEffects from './ComponentHarnessEffects.vue'
import ComponentHarnessOverlay from './ComponentHarnessOverlay.vue'
import ComponentStory from './ComponentStory.vue'
</script>

<template>
  <ComponentHarness>
    <ComponentHarnessEffects>
      <ComponentStory />
    </ComponentHarnessEffects>
    <ComponentHarnessOverlay />
  </ComponentHarness>
</template>

// src/harness/svelte/DefaultHarness.svelte
<script lang="ts">
  import ComponentHarness from './ComponentHarness.svelte'
  import ComponentHarnessEffects from './ComponentHarnessEffects.svelte'
  import ComponentHarnessOverlay from './ComponentHarnessOverlay.svelte'
  import ComponentStory from './ComponentStory.svelte'
</script>

<ComponentHarness>
  <ComponentHarnessEffects>
    <ComponentStory />
  </ComponentHarnessEffects>
  <ComponentHarnessOverlay />
</ComponentHarness>
